language: python
python:
- '3.6'
sudo: required
addons:
  ssh_known_hosts: ec2-52-206-3-72.compute-1.amazonaws.com
services:
- docker
before_install:
- wget -q $SSH_HELPER
- openssl aes-256-cbc -K $encrypted_2937cbc2de8e_key -iv $encrypted_2937cbc2de8e_iv
  -in coyote.enc -out coyote -d
- eval "$(ssh-agent -s)"
- chmod 600 coyote
- ssh-add coyote
- echo -e "db_host=$db_host\ndb_user=$db_user\ndb_passwd=$db_passwd\ndb_prod=$db_prod\nCAPTCHA_KEY_SERVER=$CAPTCHA_KEY_SERVER"| envsubst > env.list
- wget -qO- 'https://cli.netlify.com/download/latest/linux' | tar xz
- curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
- sudo apt-get install -y nodejs
- sudo apt-get install -y build-essential
- sudo npm install -g bower
install:
- pip install -r requirements.txt
before_script:
- chmod 700 run.sh
script:
- flake8 . --count --max-complexity=16 --show-source --statistics
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh
